name: Doc Previews Cleanup

on:
  schedule:
    - cron: "30 5 * * 1"
  workflow_dispatch:
    inputs:
      lookback:
        description: 'Number of days to keep previews'
        required: false
        default: '3'

# Ensure that only one "Doc Previews Cleanup" workflow is force pushing at a time
concurrency:
  group: doc-preview-cleanup
  cancel-in-progress: false

jobs:
  doc-preview-cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Cleanup previews older than lookback days and push
        run: |
          git config user.name "Documenter.jl"
          git config user.email "documenter@juliadocs.github.io"
          lookback="${{ github.event.inputs.lookback }}"
          echo "Deleting previews older than ${lookback} days..."
          # Remove files older than the specified lookback
          find previews/ -type f -mtime +${lookback} -print0 \
            | xargs -0 git rm -f || true
          # Remove empty directories
          find previews/ -type d -empty -print0 \
            | xargs -0 git rm -rf || true
          # Commit changes if any
          if git diff --quiet; then
            echo "No previews to delete."
          else
            git commit -m "Cleanup previews older than ${lookback} days"
          fi
          # Create a fresh orphan branch to drop history
          git branch gh-pages-new $(echo "delete history" | git commit-tree HEAD^{tree})
          git push --force origin gh-pages-new:gh-pages
